### PR TITLE
(SUP-1969) Enable metrics shipping for all system types

### LINKED ISSUE #48: System Metrics should allow for shipping to metrics servers
## Use Case
System metrics are only stored locally on the system they are collected on. As an administrator, I have configured a metrics server and would like to ship the system metrics to my metrics server. 

## Describe the Solution You Would Like
Add metrics shipping options to the `puppet_metrics_collector::system` class, similar to https://github.com/puppetlabs/puppetlabs-puppet_metrics_collector#metrics-server-parameters

### PR DESCRIPTION
**Pull request by jarretlavallee**
This PR adds the same metrics shipping configuration for all of the system types. It moves the logic for this that was in pe_metric out to a function and leverages it across the different system metric collection types. The metric collection scripts were updated to allow a `--print` CLI argument to be consistent.

Resolves #48

### CODE REVIEW

**Comment by MartyEwings** [comment]
looks like its only failing because getvar() is not core in puppet 5

**Comment by jarretlavallee** [comment]
I used it as a hack, so there may be a better way to do that part anyway. Without stdlib it is a bit more difficult. I wanted to enable to system metrics class to use the parameters from the main class. The problem is that we specifically set these up so they can be independent. 

This is a low-priority PR, I wrote it up last weekend since I noticed that I was missing some data in InfluxDB. I was able to use this PR to ship metrics to my InfluxDB/Grafana setup in my Kubernetes cluster. It could provide a mechanism for supporting better metrics in the dashboard without leveraging telegraf.

**Comment by MartyEwings** [comment]
once https://github.com/puppetlabs/puppet_metrics_dashboard/pull/147 is merged this will run only on 6/7 so wouldn't be an issue, I think also the system timers PR will officially deprecate puppet 5

**Comment by jarretlavallee** [comment]
This has been rebased on `main`.

**Comment by m0dular** [comment]
@MartyEwings @jarretlavallee Is this something we want in before the release?

**Comment by jarretlavallee** [comment]
@m0dular If possible. I am not sure how many customers will benefit from it, but there will be some that can get postgres metrics into Splunk. 

The biggest driver for me to want this is that I use it in my lab and I have to keep rebasing it.

**Review by MartyEwings — APPROVED** [review]

**Pull request merged**
