### PR TITLE
Sup 2428 ci migration

### PR DESCRIPTION
**Pull request by m0dular**

### CODE REVIEW

**Comment by MartyEwings** [comment]
@m0dular The workflows wont run on first commit from a fork, I don't know wether we should commit to MAIN and resolve any issues post commit, or merge into a branch and check there first before promoting to MAIN, what do you think?

**Comment by m0dular** [comment]
Ah I see.  We could do it like `ca_extend` where I push the feature to the `puppetlabs` fork and then it should work?  I'll try it out today.

**Comment by m0dular** [comment]
Pushing to the `puppetlabs` fork in #98 has kicked this off :+1:

**Comment by MartyEwings** [comment]
@m0dular this looks to be mostly styling changes in newer ruby, I think

`14 files inspected, 448 offenses detected, 359 offenses auto-correctable`

The 359 can be corrected by running "pdk validate -a" then we can see whats left over after that

**Comment by MartyEwings** [comment]
@m0dular iv checked out your branch, and ran the ruby auto-correct, it fixed a lot, but its left some styling and linting "warnings" which are likely to make the tests here exit with non - 0, the Unit tests are passing locally however.

I can commit these changes to your branch if you like, and we can see how far it gets after that? if it still fails, we may have some ruby syntax to brainstorm and correct

**Review by MartyEwings — CHANGES_REQUESTED** [review]
pdk valiate -a to auto correct some of the styling issues in ruby, then validate once more to see if there are any further warnings we may have to correct manually

**Review by MartyEwings — DISMISSED** [review]

**Pull request merged**
