### PR TITLE
(SLV-767) Updated measurement tagging

### PR DESCRIPTION
**Pull request by RandellP**
Needs to be merged at the same time as https://github.com/puppetlabs/puppet_metrics_dashboard/pull/89
That will update the graphs to consume the date this will now produce

Fixed regex that looked for puppet_server instead of puppetserver
Added regex's for bolt and ace
This means all of the services consistently get replaced and tagged instead of just some.
removed the gc-stats regex as it wasn't used and was making it harder to make graphs using it.

### CODE REVIEW

**Comment by johnduarte** [comment]
@RandellP it looks like this needs a rebase.

**Comment by jarretlavallee** [comment]
👍

**Comment by jarretlavallee** [comment]
Are we good to merge this? It seems like a good fit for the major release with #47.

**Comment by RandellP** [comment]
Well, you need 788 to go with it, or the dashboards will be broken since the tagging changes the paths to the measurements.

**Comment by RandellP** [comment]
@tkishel @jarretlavallee With SLV-788 merged, this should get merges as well, since they work together.

**Pull request merged**
