### PR TITLE
(SUP-2499) Remove Harmful Terminology

### PR DESCRIPTION
**Pull request by MartyEwings**

### CODE REVIEW

**Comment by jarretlavallee** [comment]
There seem to be some more instances of `master` in the `Configuration for Distributed Metrics Collection` section. Lines 289 and 292

**Comment by MartyEwings** [comment]
Hmm I'll do another pass, the search I did probably didn't do case or something

**Comment by asselvakumar** [comment]
> There seem to be some more instances of `master` in the `Configuration for Distributed Metrics Collection` section. Lines 289 and 292

**Comment by MartyEwings** [comment]
@asselvakumar thanks for this, anything i the REFERENCE.MD will be autogenerated from the strings comments so doesn't need altered,

As for the workflows and code, until we refactor the plans, or Product changes the Profile names in PE we cant remove that stuff

**Review by jarretlavallee — APPROVED** [review]
🚢

**Pull request merged**
